In [1]:
import os

# change working directory to project-3 root
if os.getcwd().split('/')[-1] != 'project-3':
    os.chdir('../../../')

import pandas as pd
import numpy as np
from src.utils.mutation_matrix import normalize_matrix
from sklearn.mixture import GaussianMixture

In [2]:
df_sbs = pd.read_csv('data/processed/BRCA.SBS96.all', sep='\t', index_col=0)
df_sbs.head()

TCGA-3C-AAAU  TCGA-3C-AALI  TCGA-3C-AALJ  TCGA-3C-AALK  \
MutationType                                                           
A[C>A]A                  0             3             0             0   
A[C>A]C                  1             3             3             0   
A[C>A]G                  1             0             1             0   
A[C>A]T                  0             2             0             0   
A[C>G]A                  0             1             1             0   

              TCGA-4H-AAAK  TCGA-5L-AAT0  TCGA-5L-AAT1  TCGA-5T-A9QA  \
MutationType                                                           
A[C>A]A                  1             1             3             0   
A[C>A]C                  1             0             3             0   
A[C>A]G                  0             0             1             0   
A[C>A]T                  0             0             0             0   
A[C>G]A                  0             0             3             1   

              TCGA-A1-A0SB  TCGA-A1-A0SD  ...  TCGA-UL-AAZ6  TCGA-UU-A93S  \
MutationType                              ...                               
A[C>A]A                  0             0  ...             4             4   
A[C>A]C                  0             1  ...             0             3   
A[C>A]G                  0             0  ...             1             1   
A[C>A]T                  0             0  ...             1             3   
A[C>G]A                  1             0  ...             0             1   

              TCGA-V7-A7HQ  TCGA-W8-A86G  TCGA-WT-AB41  TCGA-WT-AB44  \
MutationType                                                           
A[C>A]A                  0             0             0             1   
A[C>A]C                  2             1             0             0   
A[C>A]G                  0             0             0             0   
A[C>A]T                  0             0             0             0   
A[C>G]A                  0             0             0             0   

              TCGA-XX-A899  TCGA-XX-A89A  TCGA-Z7-A8R5  TCGA-Z7-A8R6  
MutationType                                                          
A[C>A]A                  0             1             1             0  
A[C>A]C                  0             0             0             0  
A[C>A]G                  0             0             1             0  
A[C>A]T                  0             0             0             0  
A[C>G]A                  0             1             0             1  

[5 rows x 789 columns]

In [3]:
X = np.array(df_sbs)
X

array([[0, 3, 0, ..., 1, 1, 0],
       [1, 3, 3, ..., 0, 0, 0],
       [1, 0, 1, ..., 0, 1, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       [0, 2, 1, ..., 2, 0, 0]], shape=(96, 789))

In [4]:
normalize_matrix(X, method='GMM')

array([[0., 3., 0., ..., 1., 1., 0.],
       [1., 3., 3., ..., 0., 0., 0.],
       [1., 0., 1., ..., 0., 1., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 2., 1., ..., 2., 0., 0.]], shape=(96, 789))

In [5]:
normalize_matrix(X, method='100X')

array([[0., 3., 0., ..., 1., 1., 0.],
       [1., 3., 3., ..., 0., 0., 0.],
       [1., 0., 1., ..., 0., 1., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 2., 1., ..., 2., 0., 0.]], shape=(96, 789))

In [6]:
normalize_matrix(X, method='log2')

array([[0.        , 0.0358597 , 0.        , ..., 0.03037679, 0.14963126,
        0.        ],
       [0.12007743, 0.0358597 , 0.27474519, ..., 0.        , 0.        ,
        0.        ],
       [0.12007743, 0.        , 0.09158173, ..., 0.        , 0.14963126,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.09158173, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.02390646, 0.09158173, ..., 0.06075357, 0.        ,
        0.        ]], shape=(96, 789))

In [7]:
normalize_matrix(X, method='None')

array([[0., 3., 0., ..., 1., 1., 0.],
       [1., 3., 3., ..., 0., 0., 0.],
       [1., 0., 1., ..., 0., 1., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 2., 1., ..., 2., 0., 0.]], shape=(96, 789))